### PR TITLE
Add support for variables defined in directories

### PR DESCRIPTION
**Pull request by DylanHamel**
As example:

```
inventories/lab//host_vars
├── lab_a_router_01
│   ├── interfaces.yml
│   ├── vars.yml
│   └── vault.yml
└── lab_a_router_02
    ├── s_links.yml
    ├── s_vars.yml
    ├── vars.yml
    ├── y_bfd.yml
    ├── y_interfaces.
```

### CODE REVIEW

**Comment by DylanHamel** [comment]
Tests result

```
tests/test_ansible.py::Test::test_inventory[ini] PASSED                                                                                                                                                                                                                                                                                                                                                                    [ 16%]
tests/test_ansible.py::Test::test_inventory[yaml] PASSED                                                                                                                                                                                                                                                                                                                                                                    [ 33%]
tests/test_ansible.py::Test::test_inventory[yaml2] PASSED                                                                                                                                                                                                                                                                                                                                                                   [ 50%]
tests/test_ansible.py::Test::test_inventory[yaml3] PASSED                                                                                                                                                                                                                                                                                                                                                                   [ 66%]
tests/test_ansible.py::Test::test_inventory[yaml4] PASSED                                                                                                                                                                                                                                                                                                                                                                   [ 83%]
tests/test_ansible.py::Test::test_parse_error PASSED                                                                                                                                                                                                                                                                                                                                                                        [100%]
```

**Comment by carlmontanari** [comment]
Hey @DylanHamel -- looks like a good addition! FYI, I had initially planned to also bring in things from [nornsible inventory](https://github.com/carlmontanari/nornsible/blob/master/nornsible/inventory.py), such as inventory script support.... haven't gotten around to that as I'm not really using this daily, but wanted to point it out in case there was anything else interesting in there you may want to bring into this! :)  

I'll try to get to checking this out this weekend and get back to ya with any comments/questions then. Thanks for opening this!

Carl

**Comment by DylanHamel** [comment]
Hi @carlmontanari,
I don't use `inventory script` too because we have 5000 devices and the script takes approximately 15min. So not the best way to wait 15min for each run ^^.
In any case, I can try the code!

All this can be really interesting for people wishing to migrate from Ansible to Nornir (or use both).
Cheers,
Dylan

**Comment by carlmontanari** [comment]
Closing, see #4 !

Thanks for the work on this @DylanHamel -- will get the other pr merged/updated/pypi probably this afternoon!

**Pull request closed without merging**
